# Generated by Django 4.0.4 on 2022-05-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=1500, verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, upload_to='post/', verbose_name='Изображение')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('blog', models.SlugField(max_length=15, verbose_name='Блог')),
            ],
        ),
    ]
